# Generated by Django 6.0.5 on 2026-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
