# Generated by Django 6.0.5 on 2026-05-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_payment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
