# Generated by Django 6.0.5 on 2026-05-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                default=0, help_text="Цена в рублях", verbose_name="Цена"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(
                default=0, help_text="Цена в рублях", verbose_name="Цена"
            ),
        ),
    ]
